FROM jekyll/jekyll:3.8.5

#ENTRYPOINT [ "jekyll", "new", "." ]
#ENTRYPOINT [ "bundle", "update", "jekyll-feed" ]
#ENTRYPOINT [ "gem", "install", "jekyll-theme-midnight" ]
#ENTRYPOINT [ "bundle", "update", "jekyll-theme-midnight" ]
#ENTRYPOINT [ "bundle", "install" ]
ENTRYPOINT [ "jekyll", "serve", "--force_polling" ]